# Generated by Django 4.1.2 on 2022-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
