# Generated by Django 4.1.2 on 2022-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_category_options_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
