# Generated by Django 4.1.2 on 2022-10-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
